MiniCRM/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MiniCRM.Models
{
    public class ContactViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Comment { get; set; }

        public decimal Mobile { get; set; }
    }
}

MiniCRM/Areas/Member/Controllers/ContactController.cs
using CRMBAL;
using CRMUtility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRMModel;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;
using System.IO;
using System.Data;
using System.Text.RegularExpressions;
using System.Text;
using CRMEntity;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Hosting;

namespace MiniCRM.Areas.Member.Controllers
{
    [Authorize(Roles = "Member")]
    public class ContactController : Controller
    {
        #region ---Json Method---
        [HttpGet]
        public JsonResult FetchContact(string SearchText)
        {
            var response = Contact_BAL.GetConatctAutoComplete(UserSession.UserId, SearchText);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult FetchLastName(string SearchText)
        {
            var response = Contact_BAL.GetLastNameAutoComplete(UserSession.UserId, SearchText);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult FetchCity(string SearchText)
        {
            var response = Contact_BAL.GetCityAutoComplete(UserSession.UserId, SearchText);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetCustomerType()
        {
            var response = Contact_BAL.GetCustomerTypes();
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetContactList()
        {
            var data = HttpContext.Request.QueryString;

            var list = Contact_BAL.GetContactJsGridList(data, UserSession.UserId, 0);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetContactDetails(long id)
        {
            List<SP_Select_Contact> select_Contacts = new List<SP_Select_Contact>();
            select_Contacts = Contact_BAL.GetContacts(id, UserSession.UserId, id);
            var data = select_Contacts.FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);

        }
        #endregion
        // GET: Member/Contact
        public ActionResult Index()
        {

            string dir = HostingEnvironment.MapPath("~/Uploads");
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            return View();
        }
        public void FillDropDown()
        {
            ViewBag.CustomerTypeList = Contact_BAL.GetCustomerTypes();
        }
        public ActionResult ManageContact(long id = 0, long ParentId = 0)
        {
            SP_Select_Contact _Contact = new SP_Select_Contact();
            try
            {


                if (id > 0)
                {

                    var response = Contact_BAL.GetContacts(ParentId, UserSession.UserId, id);
                    if (response != null)
                    {
                        if (response.Count() > 0)
                        {
                            _Contact = response.FirstOrDefault();
                        }
                    }
                }
                else
                {
                    _Contact.ParentContactId = ParentId;
                }
            }
            catch (Exception ex)
            {

            }
            FillDropDown();
            return View(_Contact);
        }
        [HttpPost]
        public JsonResult ManageContact(SP_Select_Contact mdl)
        {
            Response_mdl response = new Response_mdl();
            if (mdl.Id > 0)
            {
                response = Contact_BAL.VerifyMaster("Modify", mdl).Result;

            }
            else
            {
                int ContactCount = 0; long ParentContactId = 0;
                if (mdl.ParentContactId == null || mdl.ParentContactId == 0)
                {
                    ParentContactId = mdl.Id;
                }
                else
                {
                    ParentContactId = mdl.ParentContactId;
                }
                var select_Contacts = Contact_BAL.GetContacts(ParentContactId, UserSession.UserId, 0);
                if (select_Contacts != null)
                {
                    ContactCount = select_Contacts.Count();
                }
                if (ContactCount < 3)
                {
                    response = Contact_BAL.VerifyMaster("Add", mdl).Result;
                }
                else
                {
                    response.IsSuccess = false; response.IsErrorOccur = true;
                    response.Message = "You Can't add Contact";

                }

            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ManageCallContact(long id = 0, long ParentId = 0)
        {
            SP_Select_Contact _Contact = new SP_Select_Contact();
            try
            {
                if (ParentId == 0) { ParentId = id; }
                var response = Contact_BAL.GetContacts(ParentId, UserSession.UserId, id);
                if (id > 0)
                {

                    if (response != null)
                    {
                        if (response.Count() > 0)
                        {
                            _Contact = response.FirstOrDefault();
                        }
                    }
                }
                else
                {
                    var cnt = response.FirstOrDefault();
                    if (cnt != null)
                    {
                        _Contact.CityId = cnt.CityId;
                        _Contact.CityName = cnt.CityName;
                        _Contact.OrganisationId = cnt.OrganisationId;
                        _Contact.OrganisationName = cnt.OrganisationName;
                        _Contact.IndustryType = cnt.IndustryType;
                        _Contact.IndustryTypeId = cnt.IndustryTypeId;

                    }
                    _Contact.ParentContactId = ParentId;
                }
            }
            catch (Exception ex)
            {

            }
            FillDropDown();
            return PartialView("_CreateOrUpdate", _Contact);
        }
        public ActionResult ContactDetails(long id = 0, long ParentId = 0)
        {
            List<SP_Select_Contact> select_Contacts = new List<SP_Select_Contact>();
            try
            {
                select_Contacts = Contact_BAL.GetContacts(ParentId, UserSession.UserId, id);
            }
            catch (Exception ex)
            {

                throw;
            }
            return View(select_Contacts);
        }
        public ActionResult ContactDetailsPartial(long id = 0, long ParentId = 0)
        {
            List<SP_Select_Contact> select_Contacts = new List<SP_Select_Contact>();
            try
            {
                select_Contacts = Contact_BAL.GetContacts(ParentId, UserSession.UserId, id);
            }
            catch (Exception ex)
            {

                throw;
            }
            return PartialView("_ContactDetails", select_Contacts);
        }
        public ActionResult ImportContactPartial()
        {
            return PartialView("_ContactImport");
        }

        public string ImportContactDetail(HttpPostedFileBase ResponseDocument)
        {
            try
            {
                string Status = string.Empty;

                if (Request.Files.Count > 0)
                {
                    if (Request.Files[0].ContentLength > 0)
                    {
                        HttpPostedFileBase postedFile = Request.Files[0];
                        string filename = "Doc_" + Guid.NewGuid().ToString();
                        string strLocation = HttpContext.Server.MapPath("~/Uploads");
                        Request.Files[0].SaveAs(strLocation + @"\" + filename + Path.GetExtension(postedFile.FileName));
                        DataTable CsvData = GetDataTabletFromCSVFile(strLocation + @"\" + filename + Path.GetExtension(postedFile.FileName));
                        Session["Path"] = strLocation + @"\" + filename + Path.GetExtension(postedFile.FileName);
                        if (CsvData != null && CsvData.Rows.Count > 0)
                        {
                            CsvData.Rows.RemoveAt(0);
                            Status = FillContactModel(CsvData);
                            if (Status == "Success")
                            {
                                ViewBag.successmsg = "Contact have been successfully saved.";
                                return "Success";
                            }
                        }
                        else
                        {
                            //return "Problem occurred while insert Supplier wise Location,Try again.";
                            ViewBag.errormsg = "Problem occurred while change Contact ,Try again.";
                            return "Failed";
                        }
                    }
                    else
                    {
                        ViewBag.errormsg = "File is Empty.";
                        return "Failed";
                        //return "File is Empty.";
                    }

                }
                else
                {
                    ViewBag.errormsg = "Please Upload a CSV File.";
                    //return "Please Upload a CSV File.";
                    return "InCorrectFile";
                }
                return "Success";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        public ActionResult Download()
        {
            string Path = Server.MapPath("~/Content/Sample/Sample.csv");
            return File(Path,"text/csv", "Sample.csv");
        }

        public static DataTable GetDataTabletFromCSVFile(string FilePath)
        {

MiniCRM/Areas/Member/Views/Contact/ContactDetails.cshtml
@model IEnumerable<CRMModel.CustomEntity.SP_Select_Contact>

@{
    ViewBag.Title = "ContactDetails";
    Layout = "~/Areas/Member/Views/Shared/_MemberLayout.cshtml";
}

MiniCRM/Areas/Member/Views/Contact/ManageContact.cshtml
@model CRMModel.CustomEntity.SP_Select_Contact

@{
    ViewBag.Title = "ManageContact";
    Layout = "~/Areas/Member/Views/Shared/_MemberLayout.cshtml";
}

MiniCRM/Areas/Member/Views/Contact/_ContactDetails.cshtml
@model IEnumerable<CRMModel.CustomEntity.SP_Select_Contact>
@{
	Layout = "";
}
<table class="table table-bordered m-0  " id="calltable">
	<thead>
		<tr>
			<th></th>
			<th>Action</th>
			<th>Organization</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Phone1</th>
			<th>Phone2</th>
			<th>Extn</th>
			<th>Designation</th>
			<th>City</th>
			@*<th>Unit No</th>
			<th>Street</th>
			<th>Pin Code</th>*@
			<th>Email1</th>
			<th>Email2</th>
			<th>Chat1</th>
			<th>Chat2</th>
			<th>Address</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.ToList())
		{
			<tr>
				<td></td>
				<td><a onclick='OpenContactDialog(@item.Id,@item.ParentContactId,"dlgContact")'><i class="fas fa-pencil-alt"></i></a></td>
				<td>@item.OrganisationName</td>
				<td>@item.FirstName</td>
				<td>@item.LastName</td>
				<td>@item.PrimaryPhoneNo</td>
				<td>@item.PhoneNo2</td>
				<td>@item.Extn</td>
				<td>@item.Designation</td>
				<td>@item.CityName</td>
				@*<td></td>
				<td>@item.Street</td>
				<td>@item.PinCode</td>*@
				<td>@item.PrimaryEmail</td>
				<td>@item.ScondaryEmail</td>
				<td>@item.Chat1</td>
				<td>@item.Chat2</td>
                <td>
                    @item.UnitNo,@item.Street,  @item.PinCode
                </td>
			</tr>
		}

	</tbody>
</table>

<script>
	$(function () {
		$("#calltable").DataTable({
			"responsive": true,
			"autoWidth": true,
			"ordering": false,
			"searching": false,
			"paging": false,
			"info": false
		});
	});
</script>

MiniCRM/Areas/Member/Views/Contact/_ContactImport.cshtml
@{
    Layout = "";

}
<div class="row">
    <div class="col-md-12">
		<div class="custom-file">
			<input type="file" id="ContactPath" title="Browse" value="Browse" class="custom-file-input" />
			<label class="custom-file-label" for="customFile">Choose file</label>
		</div>
    </div>

</div>
<div class="row" style="margin-top:5px;">
	<div class="col-md-3">

			<form id="_import" method="post" action='@Url.Action("ImportContactDetail", "Contact")'></form>
			<input type="button" title="Import" value="Import" class="btn btn-primary" onclick="Importdata();" />

	</div>
</div>
<script>
	$(document).ready(function () {
		bsCustomFileInput.init();
	});
</script>

MiniCRM/Areas/Member/Views/Contact/_CreateOrUpdate.cshtml
@model CRMModel.CustomEntity.SP_Select_Contact
@{
	Layout = "";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "frmManageContact" }))
{
	@*@Html.Partial("_CreateOrUpdate", Model)*@
	@Html.HiddenFor(model => model.ParentContactId)
	@Html.HiddenFor(model => model.Id)
	@Html.HiddenFor(model => model.OrganisationId)
	@Html.HiddenFor(model => model.DesignationId)
	@Html.HiddenFor(model => model.CityId)
	@Html.HiddenFor(modl=>Model.IndustryTypeId)
<div class="row">
	<div class="col-md-3">
		<div class="form-group">
			<label>Organization <span class="text-danger">*</span></label>
			@Html.TextBoxFor(model => model.OrganisationName, new { @class = "form-control" })
			@Html.HiddenFor(model => model.OrganisationId, new { id = "hdnOrganisationId" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>First Name <span class="text-danger">*</span></label>
			@Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Last Name <span class="text-danger">*</span></label>
			@Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Designation <span class="text-danger">*</span></label>
			@Html.TextBoxFor(model => model.Designation, new { @class = "form-control" })
			@Html.HiddenFor(model => model.DesignationId, new { id = "hdnDesignationId" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Phone1</label>
			@Html.TextBoxFor(model => model.PrimaryPhoneNo, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Phone2</label>
			@Html.TextBoxFor(model => model.PhoneNo2, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Extn.</label>
			@Html.TextBoxFor(model => model.Extn, new { @class = "form-control" })
		</div>
	</div>
	
	
	<div class="col-md-3">
		<div class="form-group">
			<label>Email1</label>
			@Html.TextBoxFor(model => model.PrimaryEmail, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Email2</label>
			@Html.TextBoxFor(model => model.ScondaryEmail, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Chat1</label>
			@Html.TextBoxFor(model => model.Chat1, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Chat2</label>
			@Html.TextBoxFor(model => model.Chat2, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Address Line 1</label>
			@Html.TextBoxFor(model => model.UnitNo, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Address Line 2</label>
			@Html.TextBoxFor(model => model.Street, new { @class = "form-control" })
		</div>
	</div>
	
	<div class="col-md-3">
		<div class="form-group">
			<label>City <span class="text-danger">*</span></label>
			@Html.TextBoxFor(model => model.CityName, new { @class = "form-control" })
			@Html.HiddenFor(model => model.CityId, new { id = "hdnCityId" })
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<label>Pin Code</label>
			@Html.TextBoxFor(model => model.PinCode, new { @class = "form-control" })
		</div>
	</div>
	<div class="col-md-3" style="display:none;">
		<div class="form-group">
			<label>Customer Type</label>
			@Html.DropDownListFor(model => model.CustomerTypeId, new SelectList(ViewBag.CustomerTypeList, "Id", "CustomerType", Model.CustomerTypeId), "Select", new { @class = "form-control" })
		</div>
	</div>
</div>
	<div class="row">
		<div class="col-md-2">
			<input type="button" value="Save" id="btnContactSave" class="btn btn-primary" onclick="SaveContactDetails();" />
		</div>
		 
	</div>
}
<script>
	$(document).ready(function () {
		$("#OrganisationName")
			.bind("keydown", function (event) {

				if (event.keyCode == 188) {
					$(this).val('');
					event.preventDefault();
				}
				if (event.keyCode === $.ui.keyCode.TAB &&
					$(this).data("ui-autocomplete").menu.active) {
					event.preventDefault();
				}

			})
			.autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Member/Organization/FetchOrganization',
						dataType: "json",
						method: "GET",
						data: {
							SearchText: extractLast(request.term)
						},
						success: function (data) {
							console.log(data);
							response(data);
						}
					});
				},
				minLength: 2,
				change: function (event, ui) {
					/*if (!ui.item) {
						this.value = '';
						$(this).val('');
						$(this).prop('placeholder', "No Match Found");
					}*/
				},
				select: function (event, ui) {
					event.preventDefault();
					$(this).val(ui.item.label);
					$("#OrganisationId").val(ui.item.value);
					if (ui.item.value != 0) {
						if (ui.item.label.indexOf("No Match Found") < 0) {

							$(this).val(ui.item.label);
							$("#OrganisationId").val(ui.item.value);
						}
					}
					else {
						//this.value = '';
						$("#OrganisationId").val("0");
					}
				},
				focus: function () {
					// prevent value inserted on focus
					return false;
				}
			}).autocomplete("instance")._renderItem = function (ul, item) {
				return $("<li>")
					.append("<div>" + item.label + "</div>")
					.appendTo(ul);
			};
		$("#Designation")
			.bind("keydown", function (event) {

				if (event.keyCode == 188) {
					$(this).val('');
					event.preventDefault();
				}
				if (event.keyCode === $.ui.keyCode.TAB &&
					$(this).data("ui-autocomplete").menu.active) {
					event.preventDefault();
				}

			})
			.autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Member/Designation/FetchDesignation',
						dataType: "json",
						method: "GET",
						data: {
							SearchText: extractLast(request.term)
						},
						success: function (data) {
							console.log(data);
							response(data);
						}
					});
				},
				minLength: 2,
				change: function (event, ui) {
					/*if (!ui.item) {
						this.value = '';
						$(this).val('');
						$(this).prop('placeholder', "No Match Found");
					}*/
				},
				select: function (event, ui) {
					event.preventDefault();
					$(this).val(ui.item.label);
					$("#DesignationId").val(ui.item.value);
					if (ui.item.value != 0) {
						if (ui.item.label.indexOf("No Match Found") < 0) {

							$(this).val(ui.item.label);
							$("#DesignationId").val(ui.item.value);
						}
					}
					else {
						//this.value = '';
						$("#DesignationId").val("0");
					}
				},
				focus: function () {
					// prevent value inserted on focus
					return false;
				}
			}).autocomplete("instance")._renderItem = function (ul, item) {
				return $("<li>")
					.append("<div>" + item.label + "</div>")
					.appendTo(ul);
			};
		$("#CityName")
			.bind("keydown", function (event) {

				if (event.keyCode == 188) {
					$(this).val('');
					event.preventDefault();
				}
				if (event.keyCode === $.ui.keyCode.TAB &&
					$(this).data("ui-autocomplete").menu.active) {
					event.preventDefault();
				}

			})
			.autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Member/Contact/FetchCity',
						dataType: "json",
						method: "GET",
						data: {
							SearchText: extractLast(request.term)
						},
						success: function (data) {
							console.log(data);
							response(data);
						}
					});
				},
				minLength: 2,
				change: function (event, ui) {
					/*if (!ui.item) {
						this.value = '';
						$(this).val('');
						$(this).prop('placeholder', "No Match Found");
					}*/
				},
				select: function (event, ui) {
					event.preventDefault();
					$(this).val(ui.item.label);
					$("#CityId").val(ui.item.value);
					if (ui.item.value != 0) {
						if (ui.item.label.indexOf("No Match Found") < 0) {

							$(this).val(ui.item.label);
							$("#CityId").val(ui.item.value);
						}
					}
					else {
						//this.value = '';
						$("#CityId").val("0");
					}
				},
				focus: function () {
					// prevent value inserted on focus
					return false;
				}
			}).autocomplete("instance")._renderItem = function (ul, item) {
				return $("<li>")
					.append("<div>" + item.label + "</div>")
					.appendTo(ul);
			};

	});

</script>