MiniCRM/Areas/Member/Controllers/CallsController.cs
using CRMBAL;
using CRMModel;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;
using CRMUtility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniCRM.Areas.Member.Controllers
{
    [Authorize(Roles = "Member")]
    public class CallsController : Controller
    {
        #region --Json Method--
        public JsonResult GetCallList(string id)
        {
            var data = HttpContext.Request.QueryString;
            long IndustryId = 0;
            if (!String.IsNullOrEmpty(id) && id != "undefined")
            {
                IndustryId = Convert.ToInt64(id);
            }
            Session["IndustryId"] = IndustryId;
            var list = Call_BAL.GetCallJsGridList(data, UserSession.UserId, IndustryId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getLastCallDetails(string id)
        {
            var data = HttpContext.Request.QueryString;
            long IndustryId = 0;
            if (!String.IsNullOrEmpty(id) && id != "undefined")
            {
                IndustryId = Convert.ToInt64(id);
            }
            var list = Call_BAL.GetCallJsGridList(data, UserSession.UserId, IndustryId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        #endregion
        public void FillDropDown()
        {
            var IndustryList = Industry_BAL.GetIndustries(UserSession.UserId);
            ViewBag.IndustryList = IndustryList;
            ViewBag.CustomerTypeList = Contact_BAL.GetCustomerTypes();
            ViewBag.MeetingTypeList = Call_BAL.GetMeetingType();
            ViewBag.RatingList = Common_BAL.RatingDropDown();
            var CallTypeList = Call_BAL.GetCallType();
            ViewBag.CallTypeList = CallTypeList;

        }
        // GET: Member/Calls
        public ActionResult Index()
        {
            FillDropDown();
            return View();
        }
        [HttpPost]
        public JsonResult ManageCall(SP_Select_Call mdl, string IndustryTypeId)
        {
            Response_mdl response = new Response_mdl();
            bool IsAllowed = false;
            var UserRestriction = Common_BAL.VerifyUserAllowToPerformAction(En_RestrictionKey.Call.ToString(), UserSession.UserId, ref IsAllowed);
            if (!String.IsNullOrEmpty(mdl.FirstName))
            {
                if (!String.IsNullOrEmpty(IndustryTypeId))
                {
                    mdl.IndustryTypeId = Convert.ToInt64(IndustryTypeId);
                }
                //bool IsAleradyExists = Industry_BAL.IsIndustryAleradyExists(mdl.IndustryType, mdl.Id);
                if (mdl.CallId > 0)
                {

                    response = Call_BAL.VerifyMaster("Modify", mdl).Result;
                }
                else
                {
                    if (IsAllowed)
                    {
                        response = Call_BAL.VerifyMaster("Add", mdl).Result;
                    }
                    else {
                        response.IsSuccess = false;
                        response.Message = "You have reached your limit please contact to administrator.";
                    }
                }
                if (response != null)
                {

                    /*  ViewBag.Op_Message = response.Message;
                      if (response.IsSuccess && response.Id > 0)
                      {
                          ViewBag.Type = "1";
                          //return RedirectToAction(nameof(Index));
                      }
                      else
                      {
                          ViewBag.Type = "2";
                          //ModelState.AddModelError(String.Empty, response.Message);
                      }*/
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Name Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult CommonAction(string ActionType, string RefrenceId)
        {
            Response_mdl response = new Response_mdl();
            if (!String.IsNullOrEmpty(RefrenceId))
            {
                //bool IsAleradyExists = Industry_BAL.IsIndustryAleradyExists(mdl.IndustryType, mdl.Id);
                if (ActionType == "MissCall")
                {
                    SP_Select_Call mdl = new SP_Select_Call();// { CallId = Convert.ToInt64(RefrenceId), IsCallNotReceived = true }
                    mdl = Call_BAL.GetLastCallHistory(Convert.ToInt64(RefrenceId));
                    mdl.IsCallNotReceived = true;
                    response = Call_BAL.AddCallHistory(mdl).Result;
                }
                if (response != null)
                {

                    /*ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                        //return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Type = "2";
                        //ModelState.AddModelError(String.Empty, response.Message);
                    }*/
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Reference Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);

        }
        public ActionResult CallDetails(long id = 0)
        {
            FillDropDown();
            CallDetails_mdl mdl = new CallDetails_mdl();
            try
            {
                if (id == 0)
                {
                    return RedirectToAction("Index");
                }
                mdl = Call_BAL.GetLastCallDetail(mdl, UserSession.UserId, 0, id);
                if (mdl != null)
                {
                    List<SP_Select_Contact> select_Contacts = new List<SP_Select_Contact>();
                    select_Contacts = Contact_BAL.GetContacts(mdl.LastCall.ContactId, UserSession.UserId, 0);
                    mdl.Contacts = select_Contacts;
                    var Products = Contact_BAL.GetContactProduct(mdl.LastCall.ContactId);
                    mdl.Products = Products;
                }

            }
            catch (Exception ex)
            {

                throw;
            }
            return View(mdl);
        }
        [HttpPost]
        public ActionResult CallDetails(CallDetails_mdl mdl)
        {
            Response_mdl response = new Response_mdl();
            if (mdl.LastCall.LastCallHistoryId > 0)
            {
                response = Call_BAL.UpdateCallDetails(mdl.LastCall).Result;
                if (response != null)
                {

                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                        //return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Type = "2";
                        //ModelState.AddModelError(String.Empty, response.Message);
                    }
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = Call_BAL.IsCallExists(id);
            if (IsExists)
            {
                var Op = Call_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("Index");
        }
        public ActionResult CallHistory(long id = 0, long ContactId = 0, long CallId = 0)
        {
           List<SP_Select_Call> mdl = new List<SP_Select_Call>();
            try
            {
                mdl = Call_BAL.GetCallHistory(UserSession.UserId, CallId);
            }
            catch (Exception ex)
            {

            }
            return PartialView("_CallHistoryDetail", mdl);

        }

    }
}

MiniCRM/Areas/Member/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRMBAL;
using CRMUtility;
using CRMModel;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;

namespace MiniCRM.Areas.Member.Controllers
{
    public class CityController : Controller
    {
        #region --Json Method--
        public JsonResult GetCityList()
        {
            var data = HttpContext.Request.QueryString;
            var list = City_BAL.GetCityJsGridList(data, UserSession.UserId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        #endregion
        // GET: Member/City
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ManageCity(SP_Select_City mdl)
        {
            Response_mdl response = new Response_mdl();
            if (!String.IsNullOrEmpty(mdl.CityName))
            {
                bool IsAleradyExists = City_BAL.IsCityAleradyExists(mdl.CityName, mdl.Id,UserSession.UserId);
                if (mdl.Id > 0)
                {
                    if (!IsAleradyExists)
                    {
                        response = City_BAL.Update(mdl).Result;

                    }
                }
                else
                {
                    if (!IsAleradyExists)
                    {
                        response = City_BAL.Add(mdl).Result;
                    }
                }
                if (response != null)
                {

                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                        //return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Type = "2";
                        //ModelState.AddModelError(String.Empty, response.Message);
                    }
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "City Type Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = City_BAL.IsCityExists(id);
            if (IsExists)
            {
                var Op = City_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("Index");
        }
    }
}

MiniCRM/Areas/Member/Controllers/ProductController.cs
using CRMBAL;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;
using CRMUtility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniCRM.Areas.Member.Controllers
{
    [Authorize(Roles = "Member")]
    public class ProductController : Controller
    {
        #region --Json Method--
        public JsonResult GetProductList()
        {
            var data = HttpContext.Request.QueryString;
            var list = Product_BAL.GetProductJsGridList(data, UserSession.UserId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult FetchProduct(string SearchText)
        {
            var response = Product_BAL.GetProductAutoComplete(UserSession.UserId, SearchText);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion
        // GET: Member/Product
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ManageProduct(SP_Select_Product mdl)
        {
            Response_mdl response = new Response_mdl();
            if (!String.IsNullOrEmpty(mdl.ProductName))
            {
                bool IsAleradyExists = Product_BAL.IsProductAleradyExists(mdl.ProductName, mdl.Id);
                if (mdl.Id > 0)
                {
                    if (!IsAleradyExists)
                    {
                        response = Product_BAL.Update(mdl).Result;

                    }
                }
                else
                {
                    if (!IsAleradyExists)
                    {
                        response = Product_BAL.Add(mdl).Result;
                    }
                }
                if (response != null)
                {

                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                        //return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Type = "2";
                        //ModelState.AddModelError(String.Empty, response.Message);
                    }
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Industry Type Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = Industry_BAL.IsIndustryExists(id);
            if (IsExists)
            {
                var Op = Industry_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("Index");
        }
        public ActionResult ManageContactProduct(long id = 0, long ContactId = 0, long CallId = 0)
        {
            return View();
        }
        public void FillDropDown()
        {

            ViewBag.RatingList = Common_BAL.RatingDropDown();

        }
        [HttpPost]
        public JsonResult ManageContactProduct(SP_Select_ContactProduct mdl)
        {
            Response_mdl response = new Response_mdl();
            if (!String.IsNullOrEmpty(mdl.ProductName))
            {
                string Values = mdl.StrValue.ToString().Replace(",", "");
                mdl.Value = Convert.ToDecimal(Values);
                if (mdl.Id > 0)
                {
                    response = Product_BAL.VerifyMaster("Modify", mdl).Result;
                }
                else
                {
                    int ProductsCount = 0;
                    var Products = Contact_BAL.GetContactProduct(mdl.ConatctId);
                    if (Products != null)
                    {
                        ProductsCount = Products.Count();
                    }
                    if (ProductsCount < 4)
                    {
                        response = Product_BAL.VerifyMaster("Add", mdl).Result;
                    }
                    else
                    {
                        response.IsSuccess = false;
                        response.IsErrorOccur = true;
                        response.Message = "You can only add 4 product";

                    }
                }
            }
            else
            {
                response.IsSuccess = false;
                response.IsErrorOccur = true;
                response.Message = "Product Name Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index");
        }
        public ActionResult ContactProduct(long id = 0, long ContactId = 0, long CallId = 0)
        {
            FillDropDown();
            SP_Select_ContactProduct mdl = new SP_Select_ContactProduct();
            try
            {
                if (id > 0)
                {
                    var Products = Contact_BAL.GetContactProduct(ContactId, id);
                    if (Products != null)
                    {
                        if (Products.Count() > 0)
                        {
                            mdl = Products.FirstOrDefault();
                        }
                    }
                }
                else
                {
                    mdl.ConatctId = ContactId;
                    mdl.CallId = CallId;
                }
            }
            catch (Exception ex)
            {

            }
            return PartialView("_CreateOrUpdateContactProduct", mdl);
        }
        public ActionResult ContactProductDetails(long id = 0, long ContactId = 0)
        {
            List<SP_Select_ContactProduct> mdl = new List<SP_Select_ContactProduct>();
            try
            {
                mdl = Contact_BAL.GetContactProduct(ContactId);
            }
            catch (Exception ex)
            {

            }
            return PartialView("_ContactProductDetails", mdl);
        }



    }
}

MiniCRM/Areas/Member/Views/Shared/_LeftNavigation.cshtml
@using CRMUtility;
  <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
	<!-- Brand Logo -->
	<a href="@Url.Action("Index","Calls",new { area="Member"})" class="brand-link">
		<img src="~/Content/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
			 style="opacity: .8">
		<span class="brand-text font-weight-light">Turant Sales</span>
	</a>
	<!-- Sidebar -->
	<div class="sidebar">
		<!-- Sidebar user panel (optional) -->
		<div class="user-panel mt-3 pb-3 mb-3 d-flex">
			<div class="image">
				<img src="~/Content/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
			</div>
			<div class="info">
				<a href="#" class="d-block">@UserSession.UserName</a>
			</div>
		</div>
		<!-- Sidebar Menu -->
		<nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
				<!-- Add icons to the links using the .nav-icon class
	with font-awesome or any other icon font library -->
				<li class="nav-item">
					<a href="@Url.Action("Index","Calls",new { area="Member"})" class="nav-link">
						<i class="nav-icon fas fa-phone-alt"></i>
						<p>
							Call Details

						</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="@Url.Action("Index","Contact",new { area="Member"})" class="nav-link">
						<i class="nav-icon fas fa-address-book"></i>
						<p>
							Contact

						</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link ">
						@*<i class="fas fa-list-alt"></i>*@
						<i class="nav-icon fas fa-list-alt"></i>
						<p>
							Master
							<i class="right fas fa-angle-left"></i>
						</p>
					</a>
					<ul class="nav nav-treeview">
						<li class="nav-item">
							<a href="@Url.Action("Index","Organization",new { area="Member"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Organization</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index","Designation",new { area="Member"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Designation</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index","City",new { area="Member"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>City</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index","Product",new { area="Member"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Product</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index","Industry",new { area="Member"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Industry</p>
							</a>
						</li>



					</ul>
				</li>

				@*<li class="nav-item">
			<a href="@Url.Action("Index","Industry",new { area="Member"})" class="nav-link">
				<i class="nav-icon fas fa-th"></i>
				<p>
					Industry

				</p>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Index","Organization",new { area="Member"})" class="nav-link">
				<i class="nav-icon fas fa-th"></i>
				<p>
					Organization

				</p>
			</a>
		</li>*@

			</ul>
		</nav>
		<!-- /.sidebar-menu -->
	</div>
	<!-- /.sidebar -->
</aside>

MiniCRM/Areas/Member/Views/Shared/_MemberLayout.cshtml
@{
	int durationInSeconds = ((System.Web.HttpContext.Current.Session.Timeout * 60));
	//durationInSeconds = 60;
	int durationInMicroSeconds = (durationInSeconds - (3 * 60)) * 1000;
	if (Session["UserId"]==null || Session["UserId"].ToString()=="0")
    {
        durationInMicroSeconds = 0;
    }
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>@ViewBag.Title</title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
	<!-- Ionicons -->
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<!-- Tempusdominus Bbootstrap 4 -->
	<link rel="stylesheet" href="~/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
	<!-- iCheck -->
	<link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
	<!-- JQVMap -->
	<link rel="stylesheet" href="~/Content/plugins/jqvmap/jqvmap.min.css">
	<link rel="stylesheet" href="~/Content/plugins/jquery-ui/jquery-ui.css" />
	<!-- jsGrid -->
	<link rel="stylesheet" href="~/Content/plugins/jsgrid/jsgrid.min.css" />
	<link rel="stylesheet" href="~/Content/plugins/jsgrid/jsgrid-theme.min.css" />
	<link rel="stylesheet" href="~/Content/plugins/select2/css/select2.min.css" />
	<link rel="stylesheet" href="~/Content/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" />
	<!-- Theme style -->
	<link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
	<!-- overlayScrollbars -->
	<link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
	<!-- Daterange picker -->
	<link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
	<!-- summernote -->
	@*<link rel="stylesheet" href="~/Content/plugins/summernote/summernote-bs4.css">*@
	<!-- Google Font: Source Sans Pro -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
	<link rel="stylesheet" href="~/Content/dist/css/customize.css">
	<!-- DataTables -->
	<link rel="stylesheet" href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
	<!-- SweetAlert2 -->
	<link rel="stylesheet" href="~/Content/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
	<!-- Toastr -->
	<link rel="stylesheet" href="~/Content/plugins/toastr/toastr.min.css" >


	<script src="~/Content/plugins/jquery/jquery.min.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

	<script src="~/Content/Common.js"></script>
	<script type="text/javascript">
		$(function (){
            setInterval(KeepSessionAlive, @durationInMicroSeconds);
        });

        function KeepSessionAlive() {
            //
			$.post("/Account/CheckSessionAliveV1",null,
                    function (url) {
                        if(url!=""){
                            window.location=url;
                        }
                    });

            //$.post("/KeepSessionAlive.ashx", null, function () {
            //    //$("#result").append("<p>Session is alive and kicking!<p/>");
            //});
        }
	</script>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        @Html.Partial("_TopNavigation")
        @Html.Partial("_LeftNavigation")
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <footer class="main-footer">
            <strong>Copyright &copy; 2020- @System.DateTime.Now.AddYears(1).Year <a href="#">Turant Sales</a>.</strong>
            All rights reserved.
            <b>Version 1.0</b>
            <div class="float-right d-none d-sm-inline-block">
                <b>Developed by <a href="www.thummartechnolab.com">TTPL</a></b>
            </div>
        </footer>
    </div>
	<!-- jQuery UI 1.11.4 -->
	<script src="~/Content/plugins/jquery-ui/jquery-ui.min.js"></script>
	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
	<script>
		$.widget.bridge('uibutton', $.ui.button)
	</script>
	<!-- Bootstrap 4 -->
	<script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
	<!-- ChartJS -->
	<script src="~/Content/plugins/chart.js/Chart.min.js"></script>
	<!-- Sparkline -->
	<script src="~/Content/plugins/sparklines/sparkline.js"></script>
	@*<!-- JQVMap -->
		<script src="~/Content/plugins/jqvmap/jquery.vmap.min.js"></script>
		<script src="~/Content/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
		<!-- jQuery Knob Chart -->
		<script src="~/Content/plugins/jquery-knob/jquery.knob.min.js"></script>*@
	<!-- daterangepicker -->
	<script src="~/Content/plugins/moment/moment.min.js"></script>
	<script src="~/Content/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
	<script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
	<!-- Tempusdominus Bootstrap 4 -->
	<script src="~/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
	<!-- Summernote -->
	@*<script src="~/Content/plugins/summernote/summernote-bs4.min.js"></script>*@
	<!-- overlayScrollbars -->
	<script src="~/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
	<!-- AdminLTE App -->
	<script src="~/Content/dist/js/adminlte.js"></script>
	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
	@*<script src="~/Content/dist/js/pages/dashboard.js"></script>*@
	<!-- AdminLTE for demo purposes -->
	<script src="~/Content/dist/js/demo.js"></script>
	<!-- jsGrid -->
	<script src="~/Content/plugins/jsgrid/jsgrid.min.js"></script>
	<script src="~/Content/plugins/jsgrid/src/jsgrid.validation.js"></script>
	<!-- Select2 -->
	<script src="~/Content/plugins/select2/js/select2.full.min.js"></script>
	<script src="~/Content/plugins/jquery-ui/jquery-ui.js"></script>
	<script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
	<script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
	<script src="~/Content/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
	<script src="~/Content/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
	<!-- SweetAlert2 -->
	<script src="~/Content/plugins/sweetalert2/sweetalert2.min.js"></script>
	<!-- Toastr -->
	<script src="~/Content/plugins/toastr/toastr.min.js"></script>
	<script>


        $(".sidebar ul a").on('click', function (e) {
            var link = $(this);

            var item = link.parent("li");

            if (item.hasClass("active")) {
                item.removeClass("active").children("a").removeClass("active");
            } else {
                item.addClass("active").children("a").addClass("active");
            }

            if (item.children("ul").length > 0) {
                var href = link.attr("href");
                link.attr("href", "#");
                setTimeout(function () {
                    link.attr("href", href);
                }, 300);
                e.preventDefault();
            }
        })
            .each(function () {
                var link = $(this);
                if (link.get(0).href === location.href) {
                    link.addClass("active").parents("li").addClass("has-treeview menu-open");
                    return false;
                }
            });
    </script>
	<style>
		.input-validation-error{
			border: 1px solid #dc0134 !important;
		}
	</style>
</body>
</html>

MiniCRM/Areas/Member/Views/Shared/_TopNavigation.cshtml
 <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
	<!-- Left navbar links -->
	<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a href="@Url.Action("Index","Calls",new { area="Member"})" class="nav-link">Calls</a>
		</li>

	</ul>
	@Html.Partial("Common/_Announcement")
	<!-- SEARCH FORM -->
	<form class="form-inline ml-3" style="display:none;">
		<div class="input-group input-group-sm">
			<input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
			<div class="input-group-append">
				<button class="btn btn-navbar" type="submit">
					<i class="fas fa-search"></i>
				</button>
			</div>
		</div>
	</form>
	<!-- Right navbar links -->
	<ul class="navbar-nav ml-auto">
		@Html.Partial("_LoginPartial")
		<!-- Messages Dropdown Menu -->

	</ul>
</nav>
<!-- /.navbar -->