MiniCRM/Areas/Admin/Controllers/AnnouncementController.cs
using CRMBAL;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;
using CRMUtility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniCRM.Areas.Admin.Controllers
{
    public class AnnouncementController : Controller
    {
        // GET: Admin/Announcement
        [Authorize(Roles = "Admin,SupperAdmin")]
        public ActionResult Index()
        {
            return View();
        }
        #region --Json Method--
        public JsonResult GetAnnouncementList()
        {
            var data = HttpContext.Request.QueryString;
            var list = Announcement_BAL.GetAnnouncementJsGridList(data, UserSession.UserId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        #endregion
        public ActionResult ManageAnnouncement(long id = 0)
        {
            SP_Select_Announcement mdl = new SP_Select_Announcement();
            if (id > 0)
            {
                mdl = Announcement_BAL.GetAnnouncementByID(id).FirstOrDefault();
            }
            return View(mdl);
        }

        [HttpPost]
        public ActionResult ManageAnnouncement(SP_Select_Announcement mdl)
        {
            Response_mdl response = new Response_mdl();
            if (ModelState.IsValid)
            {
                if (mdl.Id > 0)
                {
                    response = Announcement_BAL.Update(mdl).Result;

                }
                else
                {
                    response = Announcement_BAL.Add(mdl).Result;
                }
                if (response != null)
                {

                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                    }
                    else
                    {
                        ViewBag.Type = "2";
                    }
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Annoucement Required";
                return View(mdl);
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = Announcement_BAL.IsAnnoucementExists(id);
            if (IsExists)
            {
                var Op = Announcement_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("Index");
        }
    }
}

MiniCRM/Areas/Admin/Controllers/PackageController.cs
using CRMBAL;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;
using CRMUtility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniCRM.Areas.Admin.Controllers
{
    public class PackageController : Controller
    {
        // GET: Admin/Package
        #region --Json Method--
        public JsonResult GetPackagList()
        {
            var data = HttpContext.Request.QueryString;
            var list = Package_BAL.GetPackageJsGridList(data, UserSession.UserId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        #endregion
        [Authorize(Roles = "Admin,SupperAdmin")]
        public ActionResult Index()
        {
            return View();
        }

        public void FillDropDown()
        {
            var packageGroups = Package_BAL.GetPackageGroup();
            ViewBag.PackageGroupList = packageGroups;

        }
        public ActionResult ManagePackage(int id = 0)
        {
            SP_Select_Package mdl = new SP_Select_Package();
            FillDropDown();
            if (id > 0)
            {
                mdl = Package_BAL.GetPackageByID(id).FirstOrDefault();
            }

            return View(mdl);
        }

        [HttpPost]
        public ActionResult ManagePackage(SP_Select_Package mdl)
        {
            Response_mdl response = new Response_mdl();
            if (ModelState.IsValid)
            {
                if (mdl.Id > 0)
                {
                    response = Package_BAL.Update(mdl).Result;
                }
                else
                {
                    response = Package_BAL.Add(mdl).Result;
                }
                if (response != null)
                {

                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                    }
                    else
                    {
                        ViewBag.Type = "2";
                    }
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Package Name Required";
                return View(mdl);
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = Package_BAL.IsPackageExists(id);
            if (IsExists)
            {
                var Op = Package_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("Index");
        }
    }
}

MiniCRM/Areas/Admin/Controllers/PackageGroupController.cs
using CRMBAL;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;
using CRMUtility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRMModel;
namespace MiniCRM.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SupperAdmin")]
    public class PackageGroupController : Controller
    {
        // GET: Admin/PackageGroup
        #region --Json Method--
        public JsonResult GetPackageGroupList()
        {
            var data = HttpContext.Request.QueryString;
            var list = PackageGroup_BAL.GetPackageGroupJsGridList(data, 0);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        #endregion

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GroupDetails(long id)
        {
            PackageGroupDetails_mdl mdl = new PackageGroupDetails_mdl();
            var configList = PackageGroup_BAL.GetPackageGroupConfigurations(0, id);
            mdl.PackageGroupConfigurations = configList;
            return View(mdl);
        }
        public void FillDropDown(SP_Select_PackageGroupConfiguration mdl)
        {
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            List<string> keys = new List<string>();
            keys = Enum.GetNames(typeof(En_RestrictionKey)).ToList();
            selectListItems = keys.Select(s => new SelectListItem { Text =s, Value = s,Selected=(String.IsNullOrEmpty(mdl.RestrictionKey)?false:(mdl.RestrictionKey==s)?true:false) }).ToList();
            ViewBag.RestrictionKeyList = selectListItems;
            var Dependancy = Enum.GetNames(typeof(En_RestrictionDependency)).ToList();
            // selectListItems = new List<SelectListItem>();
            var selectList = Dependancy.Select(s => new SelectListItem { Text = s, Value = s }).ToList();
            ViewBag.RestrictionDependencyList = selectList;
        }
        public ActionResult ManageConfigurationPartial(long id=0,long PackageGroupId=0)
        {
            SP_Select_PackageGroupConfiguration mdl = new SP_Select_PackageGroupConfiguration();
            try
            {
                if(id>0)
                {
                    var configList = PackageGroup_BAL.GetPackageGroupConfigurations(id,PackageGroupId);
                    if (configList != null)
                    {
                        mdl = configList.FirstOrDefault();
                        mdl.RestrictionKey = mdl.RestrictionKey.Trim();
                        mdl.RestrictionDependency = mdl.RestrictionDependency.Trim();
                    }
                }
                else
                {
                    mdl.PackageGroupId = PackageGroupId;
                }
            }
            catch (Exception ex)
            {


            }
            FillDropDown(mdl);
            return PartialView("_ManageConfiguration", mdl);
        }

        [HttpPost]
        public JsonResult ManageConfiguration(SP_Select_PackageConfiguration mdl)
        {
           
            Response_mdl response = new Response_mdl();
            if (!String.IsNullOrEmpty(mdl.RestrictionKey))
            {
                bool IsAleradyExists = PackageConfiguration_BAL.IsPackageAleradyExists(mdl.RestrictionKey, mdl.Id);
                if (mdl.Id > 0)
                {
                    if (IsAleradyExists)
                    {
                        response = PackageConfiguration_BAL.Update(mdl).Result;

                    }
                }
                else
                {
                    if (!IsAleradyExists)
                    {
                        response = PackageConfiguration_BAL.Add(mdl).Result;
                    }
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Package Group Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult ManagePackageGroup(SP_Select_PackageGroup mdl)
        {
            Response_mdl response = new Response_mdl();
            if (!String.IsNullOrEmpty(mdl.PackageGroupName))
            {
                bool IsAleradyExists = PackageGroup_BAL.IsPackageGroupAleradyExists(mdl.PackageGroupName, mdl.Id);
                if (mdl.Id > 0)
                {
                    if (!IsAleradyExists)
                    {
                        response = PackageGroup_BAL.Update(mdl).Result;

                    }
                }
                else
                {
                    if (!IsAleradyExists)
                    {
                        response = PackageGroup_BAL.Add(mdl).Result;
                    }
                }
                /*if (response != null)
                {

                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                        //return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Type = "2";
                        //ModelState.AddModelError(String.Empty, response.Message);
                    }
                }*/
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Package Group Required";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = PackageGroup_BAL.IsPackageGroupExists(id);
            if (IsExists)
            {
                var Op = PackageGroup_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("Index");
        }

        

    }
}

MiniCRM/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRMBAL;
using CRMModel.CustomEntity;
using CRMModel.ViewModel;

namespace MiniCRM.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SupperAdmin")]
    public class UserController : Controller
    {

        #region --Json Method--
        public JsonResult GetUsersList()
        {
            var data = HttpContext.Request.QueryString;
            var list = User_BAL.GetUserJsGridList(data);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        #endregion
        // GET: Admin/User
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult Delete(long id)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = User_BAL.UserExists(id);
            if (IsExists)
            {
                var Op = User_BAL.Delete(id);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult CommonAction(int UserId, bool CurrentValue, string ActionType)
        {
            Response_mdl response = new Response_mdl();
            bool IsExists = User_BAL.UserExists(UserId);
            if (IsExists)
            {
                var Op = User_BAL.CommonAction(UserId, CurrentValue, ActionType);
                response = Op.Result;
            }
            else
            {
                response.IsSuccess = false;
                response.Message = "Record Not Found.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public void FillDropDown(long id = 0)
        {
            var PackageList = CRMBAL.Package_BAL.GetPackages();
            if (PackageList.Where(p => p.Id == id).Select(p => p.PackageName).FirstOrDefault() == "Free")
            {
                ViewBag.Packages = PackageList;
            }
            else
            {
                ViewBag.Packages = PackageList.Where(p => p.PackageName != "Free").ToList();
            }
            List<SelectListItem> items = new List<SelectListItem>();
            items = Common_BAL.GenderDropdown();
            ViewBag.GenderList = items;
        }
        public ActionResult Userdetail(long id = 0)
        {
            SP_Select_User mdl = new SP_Select_User();
            if (id > 0)
            {
                mdl = User_BAL.GetUserListById(id).FirstOrDefault();
            }
            FillDropDown(mdl.PackageId);
            return View(mdl);
        }
        [HttpPost]
        public ActionResult Userdetail(SP_Select_UserDetails mdl)
        {
            Response_mdl response = new Response_mdl();
            if (mdl.id > 0)
            {
                var userdetail = User_BAL.Update(mdl);
                response = userdetail.Result;
                if (response != null)
                {
                    ViewBag.Op_Message = response.Message;
                    if (response.IsSuccess && response.Id > 0)
                    {
                        ViewBag.Type = "1";
                    }
                    else
                    {
                        ViewBag.Type = "2";
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MiniCRM/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Content/plugins/jqvmap/jqvmap.min.css">
    <!-- jsGrid -->
    <link rel="stylesheet" href="~/Content/plugins/jsgrid/jsgrid.min.css" />
    <link rel="stylesheet" href="~/Content/plugins/jsgrid/jsgrid-theme.min.css" />
    <link rel="stylesheet" href="~/Content/plugins/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/Content/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    @*<link rel="stylesheet" href="~/Content/plugins/summernote/summernote-bs4.css">*@
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/plugins/jquery-ui/jquery-ui.css" />
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="~/Content/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="~/Content/plugins/toastr/toastr.min.css">

    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="~/Content/Common.js"></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        @Html.Partial("_TopNavigation")
        @Html.Partial("_LeftNavigation")
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <footer class="main-footer">
            <strong>Copyright &copy; 2020- @System.DateTime.Now.AddYears(1).Year <a href="#">Turant Sales</a>.</strong>
            All rights reserved.
            <b>Version 1.0</b>
            <div class="float-right d-none d-sm-inline-block">
                <b>Developed by <a href="http://www.thummartechnolab.com" target="_blank">TTPL</a></b>
            </div>
        </footer>
    </div>

    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Content/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/plugins/sparklines/sparkline.js"></script>
    @*<!-- JQVMap -->
        <script src="~/Content/plugins/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
        <!-- jQuery Knob Chart -->
        <script src="~/Content/plugins/jquery-knob/jquery.knob.min.js"></script>*@
    <!-- daterangepicker -->
    <script src="~/Content/plugins/moment/moment.min.js"></script>
    <script src="~/Content/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    @*<script src="~/Content/plugins/summernote/summernote-bs4.min.js"></script>*@
    <!-- overlayScrollbars -->
    <script src="~/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>
    <!-- jsGrid -->

    <script src="~/Content/plugins/jsgrid/jsgrid.min.js"></script>
    <!-- Select2 -->
    <script src="~/Content/plugins/select2/js/select2.full.min.js"></script>
    <script src="~/Content/plugins/jquery-ui/jquery-ui.js"></script>
    <script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="~/Content/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/Content/plugins/toastr/toastr.min.js"></script>
    <script>


     /*   $(".sidebar ul a").on('click', function (e) {
            var link = $(this);

            var item = link.parent("li");

            if (item.hasClass("active")) {
                item.removeClass("active").children("a").removeClass("active");
            } else {
                item.addClass("active").children("a").addClass("active");
            }

            if (item.children("ul").length > 0) {
                var href = link.attr("href");
                link.attr("href", "#");
                setTimeout(function () {
                    link.attr("href", href);
                }, 300);
                e.preventDefault();
            }
        })
            .each(function () {
                var link = $(this);
                if (link.get(0).href === location.href) {
                    link.addClass("active").parents("li").addClass("has-treeview menu-open");
                    return false;
                }
            });*/
    </script>
    <style>
        .input-validation-error {
            border: 1px solid #dc0134 !important;
        }
    </style>
</body>
</html>

MiniCRM/Areas/Admin/Views/Shared/_LeftNavigation.cshtml
@using CRMUtility
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="@Url.Action("Index","Home",new { area="Admin"})" class="brand-link">
        <img src="~/Content/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Turant sales</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Content/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@UserSession.UserName</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
				<!-- Add icons to the links using the .nav-icon class
	with font-awesome or any other icon font library -->
				<li class="nav-item">
					<a href="@Url.Action("Index","Home",new { area="Admin"})" class="nav-link">
						<i class="nav-icon fas fa-tachometer-alt"></i>
						<p>
							Dashboard
							@*<span class="right badge badge-danger">New</span>*@
						</p>
					</a>
				</li>
				@*<li class="nav-item has-treeview menu-open">
			<a href="#" class="nav-link active">
				<i class="nav-icon fas fa-tachometer-alt"></i>
				<p>
					Dashboard
					<i class="right fas fa-angle-left"></i>
				</p>
			</a>
			<ul class="nav nav-treeview">
				<li class="nav-item">
					<a href="./index.html" class="nav-link active">
						<i class="far fa-circle nav-icon"></i>
						<p>Dashboard v1</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="./index2.html" class="nav-link">
						<i class="far fa-circle nav-icon"></i>
						<p>Dashboard v2</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="./index3.html" class="nav-link">
						<i class="far fa-circle nav-icon"></i>
						<p>Dashboard v3</p>
					</a>
				</li>
			</ul>
		</li>*@
				<li class="nav-item">
					<a href="@Url.Action("Index","User",new { area="Admin"})" class="nav-link">
						<i class="nav-icon fas fa-user-alt"></i>
						<p>
							Users
						</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="@Url.Action("Index","Announcement",new { area="Admin"})" class="nav-link">
						<i class="nav-icon fas fa-bullhorn"></i>
						<p>
							Announcement
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview">
					<a href="#" class="nav-link">
						<i class="nav-icon fas fa-box"></i>
						<p>
							Packages
							<i class="right fas fa-angle-left"></i>
						</p>
					</a>
					<ul class="nav nav-treeview">
						<li class="nav-item">
							<a href="@Url.Action("Index","PackageGroup",new { area="Admin"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Package Group</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index","Package",new { area="Admin"})" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Package</p>
							</a>
						</li>

					</ul>
				</li>
				@*<li class="nav-item">
					<a href="@Url.Action("Index","Package",new { area="Admin"})" class="nav-link">
						<i class="nav-icon fas fa-bullhorn"></i>
						<p>
							Package
						</p>
					</a>
				</li>*@
			</ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>